//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by StrongholdTrainer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_STRONGHOLDTRAINER_DIALOG    102
#define IDR_MAINFRAME                   128
#define IDI_WOOD                        130
#define IDI_STONE                       131
#define IDI_IRON                        132
#define IDI_PITCH                       133
#define IDI_ALE                         134
#define IDI_FLOUR                       135
#define IDI_WHEAT                       136
#define IDI_HOPS                        137
#define IDI_ANISKINS                    138
#define IDI_MEAT                        139
#define IDI_FRUIT                       140
#define IDI_BREAD                       141
#define IDI_CHEESE                      142
#define IDI_SWORD                       143
#define IDI_BOW                         144
#define IDI_CROSSBOW                    145
#define IDI_SPEAR                       146
#define IDI_PIKE                        147
#define IDI_MACE                        148
#define IDI_LEATHERARM                  149
#define IDI_METALARM                    150
#define IDI_GOLD                        151
#define IDD_STOCKPILE_PAGE              153
#define IDD_RAWMATERIALS_PAGE           154
#define IDD_GRANARY_PAGE                155
#define IDD_ARMORY_PAGE                 156
#define IDB_STRONGHOLD                  156
#define IDD_MONEY_PAGE                  157
#define IDD_INFO_PAGE                   158
#define IDC_WOOD_VAL                    1000
#define IDC_INCWOOD10                   1001
#define IDC_INCWOOD100                  1002
#define IDC_STONE_VAL                   1003
#define IDC_SETWOODZERO                 1007
#define IDC_INCSTONE10                  1008
#define IDC_INCSTONE100                 1009
#define IDC_SETSTONEZERO                1010
#define IDC_IRON_VAL                    1011
#define IDC_INCIRON10                   1012
#define IDC_INCIRON100                  1013
#define IDC_SETIRONZERO                 1014
#define IDC_PITCH_VAL                   1015
#define IDC_INCPITCH10                  1016
#define IDC_INCPITCH100                 1017
#define IDC_SETPITCHZERO                1018
#define IDC_ALE_VAL                     1019
#define IDC_INCALE10                    1020
#define IDC_INCALE100                   1021
#define IDC_SETALEZERO                  1022
#define IDC_FLOUR_VAL                   1023
#define IDC_INCFLOUR10                  1024
#define IDC_INCFLOUR100                 1025
#define IDC_WHEAT_VAL                   1026
#define IDC_SETFLOURZERO                1027
#define IDC_INCWHEAT10                  1028
#define IDC_INCWHEAT100                 1029
#define IDC_SETWHEATZERO                1030
#define IDC_HOPS_VAL                    1031
#define IDC_INCHOPS10                   1032
#define IDC_INCHOPS100                  1033
#define IDC_SETHOPSZERO                 1034
#define IDC_ANISKINS_VAL                1035
#define IDC_INCANISKINS10               1036
#define IDC_INCANISKINS100              1037
#define IDC_SETANISKINSZERO             1038
#define IDC_CHK_FREEZE_MONEY            1039
#define IDC_ICONWOOD                    1040
#define IDC_LOAD_GRANARY                1041
#define IDC_GAME_STATUS                 1042
#define IDC_MEAT_VAL                    1043
#define IDC_URL                         1043
#define IDC_INCMEAT10                   1044
#define IDC_EMAIL                       1044
#define IDC_INCMEAT100                  1045
#define IDC_PLAYER                      1045
#define IDC_FRUIT_VAL                   1046
#define IDC_SETMEATZERO                 1047
#define IDC_INCFRUIT10                  1048
#define IDC_INCFRUIT100                 1049
#define IDC_SETFRUITZERO                1050
#define IDC_BREAD_VAL                   1051
#define IDC_INCBREAD10                  1052
#define IDC_INCBREAD100                 1053
#define IDC_SETBREADZERO                1054
#define IDC_CHEESE_VAL                  1055
#define IDC_INCCHEESE10                 1056
#define IDC_INCCHEESE100                1057
#define IDC_SETCHEESEZERO               1058
#define IDC_SWORD_VAL                   1059
#define IDC_INCSWORD10                  1060
#define IDC_INCSWORD100                 1061
#define IDC_CROSSBOW_VAL                1062
#define IDC_SETSWORDZERO                1063
#define IDC_INCCROSSBOW10               1064
#define IDC_INCCROSSBOW100              1065
#define IDC_SETCROSSBOWZERO             1066
#define IDC_SPEAR_VAL                   1067
#define IDC_INCSPEAR10                  1068
#define IDC_INCSPEAR100                 1069
#define IDC_SETSPEARZERO                1070
#define IDC_BOW_VAL                     1071
#define IDC_INCBOW10                    1072
#define IDC_INCBOW100                   1073
#define IDC_SETBOWZERO                  1074
#define IDC_PIKE_VAL                    1075
#define IDC_INCPIKE10                   1076
#define IDC_INCPIKE100                  1077
#define IDC_MACE_VAL                    1078
#define IDC_SETPIKEZERO                 1079
#define IDC_INCMACE10                   1080
#define IDC_INCMACE100                  1081
#define IDC_SETMACEZERO                 1082
#define IDC_LEATHERARM_VAL              1083
#define IDC_INCLEATHERARM10             1084
#define IDC_INCLEATHERARM100            1085
#define IDC_SETLEATHERARMZERO           1086
#define IDC_METALARM_VAL                1087
#define IDC_INCMETALARM10               1088
#define IDC_INCMETALARM100              1089
#define IDC_SETMETALARMZERO             1090
#define IDC_GOLD_VAL                    1103
#define IDC_INCGOLD10                   1104
#define IDC_INCGOLD100                  1105
#define IDC_INCGOLD1000                 1106
#define IDC_SETGOLDZERO                 1107
#define IDC_INCGOLD10000                1108
#define IDC_LOAD_ARMORY                 1123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
